version: 2.1

# The images that jobs can have
executors:
  panther-buildpack:
    docker:
      - image: pantherlabs/panther-buildpack:1.0.1

# Set of re-usable commands to be used across different jobs
commands:
  setup_backend:
    steps:
      - checkout
      - run:
          name: Install Go and Python libraries
          command: mage setup:go setup:python
      - run:
          name: Install prettier for CloudFormation formatting
          command: npm install prettier

  setup_frontend:
    steps:
      - checkout
      - run:
          name: Install JS dependencies
          command: mage setup:web

# The pool of jobs that that our CI will be able to run
jobs:
  validate_frontend:
    executor: panther-buildpack
    steps:
      - setup_frontend
      - run:
          name: Lint and audit web source
          command: mage test:web

  validate_backend:
    executor: panther-buildpack
    resource_class: xlarge
    steps:
      - setup_backend
      - run:
          name: Touch Swagger SDKs to prevent regeneration
          command: touch api/gateway/*/{client,models}
      - run:
          name: Lint and test the backend infrastructure
          command: mage test:cfn test:go test:python

workflows:
  version: 2
  pipeline:
    jobs:
      - validate_frontend
      - validate_backend
